def generate_proper_book_two_summaries():
    # Proper summaries for Book Two: King of the Vagabonds (140-160 words each)
    summaries = [
        # Chunk 1 - 151 words
        "Book Two opens in 1665 London with young Jack Shaftoe and his brothers Dick and Bob being cast out by their six-fingered mother to earn their keep. The boys join gangs of mudlarks who steal from ships anchored in the Thames. Their technique involves climbing anchor cables at night to lower ropes for accomplices. This dangerous work requires bribing sailors who pretend not to notice. The mudlarks devise a scheme to steal anchors and sell them back to ships, potentially causing vessels to drift and run aground. During one such attempt, Dick Shaftoe swims to cut a Dutch ship's anchor cable but becomes entangled and drowns when his brothers inadvertently pull the rope taut. This tragedy ends the Shaftoe brothers' mudlarking career. John Cole, their leader, continues the criminal enterprise but is eventually caught with his gang and sent to Newgate Prison to await trial.",
        
        # Chunk 2 - 147 words
        "At the Old Bailey, most mudlarks escape hanging by reciting Psalm 51, proving they can read and thus claiming benefit of clergy - an ancient legal loophole. However, John Cole, previously branded with a 'T' for thief, cannot use this defense. Condemned to hang at Tyburn, he asks the Shaftoe brothers to pull on his legs during execution to hasten death. In exchange, he promises hidden treasure. At the hanging, Jack notices that well-dressed condemned receive a merciful quick death with the noose knot positioned to break the neck, while the poor endure slow strangulation. The brothers fulfill their grim duty, pulling Cole's legs until he dies. The promised treasure proves false - only excrement beneath loose floorboards. However, this experience launches the brothers' new profession: they become regular fixtures at Tyburn, hired by families to perform the same service for other condemned prisoners, earning coins for hastening death.",
        
        # Chunk 3 - 149 words
        "The brothers explore Newgate Prison, learning its geography and social hierarchy. The fortress-like structure spans Holborn road, containing various wards segregated by prisoners' ability to pay. The horrific Stone Hold houses the destitute in conditions so vile that the floor cracks with the bodies of crushed lice. Wealthier prisoners enjoy the Press-Yard, drinking wine with visitors, while the Black Dog Tavern serves those with moderate means. Jack and Bob seek condemned prisoners whose families will pay for leg-pulling services at execution. They discover the castle's Condemned Hold where those awaiting hanging spend their final days. The prison operates as a complete society with its own economy, where everything from candles to food requires payment. The brothers become familiar with the rhythms of execution days, which occur eight times yearly. Their business thrives as they provide a merciful service in London's brutal justice system, establishing themselves as professionals in this grim trade.",
        
        # Chunk 4 - 152 words
        "Years pass and Jack, now grown, finds himself a soldier in the European wars. He serves as a musketeer in formations designed to protect against cavalry charges, with pikemen at the center and musketeers forming a protective square. His equipment includes a bandolier of wooden powder flasks and lead balls. The Christian army marches toward Vienna, which is besieged by Turkish forces. Jack observes the contrast between the rigid formations of Western armies and rumors of Turkish mounted archers. As they approach through Austrian valleys, the multinational force includes Poles, Bavarians, and Saxons. The army's massive logistical needs - turning barley into horseshit, as Jack cynically notes - strain resources. They bivouac in mountain valleys, awaiting the battle. Jack's transformation from London street thief to continental soldier reflects the era's social mobility through military service. The impending clash at Vienna will determine whether Christian Europe or the Ottoman Empire controls the heart of the continent.",
        
        # Chunk 5 - 148 words
        "Jack climbs to a bluff overlooking besieged Vienna, observing the tactical situation. The city appears small, overwhelmed by its own fortifications and engulfed by the Turkish camp. A cathedral with a distinctive tower dominates the skyline - its symbol of a star lodged in a crescent moon seems prophetic. The Turkish camp forms a crescent around Vienna, touching the Danube at both ends. Between besiegers and city lies a deadly zone controlled by military engineers, crisscrossed with calculated sight-lines and cannon trajectories. Vienna's modern fortifications feature angled bastions and earthworks designed to deflect artillery, making medieval walls obsolete. The Imperial Palace rises prominently, and Jack fantasizes about rescuing a figure glimpsed in a dormer window. The Turkish assault focuses on a massive bastion below the palace. Jack notes the sophisticated engineering on both sides, representing a new form of warfare where mathematics and geometry prove as important as courage and steel.",
        
        # Chunk 6 - 146 words
        "The narrative shifts to Jack's earlier military experiences, revealing how he became a soldier. After failed ventures as a highwayman and vagabond across England, he joins a regiment through typical recruitment methods of the era - essentially being shanghaied while drunk. His training in musketry and formation fighting prepares him for continental warfare. The story details the economics of military service: soldiers' pay, equipment costs, and the various ways commanders profit from their units. Jack learns the international nature of European armies, where nationality matters less than willingness to fight for pay. His regiment moves through the German states toward Austria, part of the massive Christian coalition assembling to break the Turkish siege. The journey exposes Jack to different cultures and languages, broadening his worldview beyond London's slums. Military life, despite its dangers, offers regular meals and structure previously unknown to him.",
        
        # Chunk 7 - 150 words
        "Jack's unit approaches the decisive battle at Vienna. Turkish siege works surround the city, with mining operations threatening to breach the walls. The Christian relief force must coordinate a complex assault involving multiple nationalities with different military traditions and languages. Jack observes the Turkish camp's exotic appearance - colorful tents, unfamiliar banners, and the sounds of foreign music and calls to prayer. The contrast between Christian and Islamic forces extends beyond religion to fundamental differences in military organization and tactics. Engineers on both sides have transformed warfare into a mathematical science. Jack's position in the infantry means he'll face the brutal reality of assault against prepared positions. The stakes are civilization-defining: if Vienna falls, the path to the heart of Europe lies open to Ottoman expansion. Jack's personal survival instincts conflict with his role in this historical moment. Despite his cynicism, he recognizes participating in events that will echo through history.",
        
        # Chunk 8 - 153 words
        "The battle for Vienna begins with coordinated attacks by the Christian relief force. Jack's unit advances under fire, experiencing the chaos of seventeenth-century warfare - smoke, noise, and confusion. The Polish winged hussars charge spectacularly, their wings creating an otherworldly sound that terrifies Turkish forces. Jack survives the initial assault through luck and street-fighting instincts. In the melee, he encounters and rescues a mysterious captive from the Turkish camp - a young woman who proves to be Eliza, setting up their future partnership. The Turkish army breaks and flees, leaving behind enormous plunder. Vienna is saved, marking the high-water mark of Ottoman expansion into Europe. Jack, amid the looting, secures enough wealth to transform his prospects. His rescue of Eliza intertwines their fates. The victory reshapes European politics, while for Jack personally, it marks his transition from mere survival to the possibility of advancement through audacity and luck in an era of tremendous upheaval.",
        
        # Chunk 9 - 147 words
        "Following Vienna's liberation, Jack and Eliza travel together as he discovers her remarkable background. Captured from a European noble family and enslaved in a Turkish harem, she possesses education and linguistic abilities far exceeding Jack's street knowledge. Their partnership combines his survival skills with her intelligence and social understanding. They navigate post-battle chaos, avoiding military authorities while securing portable wealth from battlefield plunder. Eliza proves invaluable in converting exotic goods into usable currency. Their relationship develops from mutual convenience into genuine affection, though vast social differences create tension. Jack introduces Eliza to European customs while she educates him in mathematics, languages, and commerce. They head west through war-torn territories, dodging deserters and brigands. Eliza's knowledge of both Christian and Islamic cultures provides advantages in trading captured Turkish goods. Their journey becomes both a physical escape from the war's aftermath and an education for both in navigating a rapidly changing world.",
        
        # Chunk 10 - 148 words
        "Jack and Eliza's westward journey continues through the fragmented Holy Roman Empire. They witness war's aftermath - destroyed villages, refugee columns, and economic disruption. Eliza's commercial acumen transforms their battlefield loot into steady profit through clever trading. She teaches Jack basic numeracy and literacy while he protects her from physical dangers. Their partnership evolves as they recognize complementary strengths. They encounter various adventures - narrow escapes from brigands, cons perpetrated on greedy merchants, and navigation of complex political boundaries. Eliza's beauty and intelligence attract unwanted attention, requiring Jack's protective skills. She begins developing her understanding of European financial systems, seeing opportunities in currency exchange and market inefficiencies. Jack, despite growing feelings for Eliza, recognizes the temporary nature of their arrangement given their disparate backgrounds. They approach the Rhine, gateway to the more stable territories of western Europe, where new opportunities and challenges await.",
        
        # Chunk 11 - 150 words
        "Crossing the Rhine marks a transition in Jack and Eliza's journey from war-torn regions to commercial centers. They reach Frankfurt, where Eliza's trading skills flourish in the city's markets and banking houses. She begins establishing connections with merchants and financiers, demonstrating remarkable aptitude for commerce. Jack feels increasingly out of place in this sophisticated environment. Their relationship strains as Eliza's ambitions grow beyond mere survival. She sees opportunities in the emerging financial instruments - bills of exchange, letters of credit, and early stock trading. Jack's role shifts from protector to assistant, a change that challenges his self-image. Eliza attracts suitors from the merchant class, forcing Jack to confront their relationship's limitations. Despite their bond forged in adversity, social realities intrude. Eliza must choose between emotional attachment to Jack and opportunities for advancement in commercial society. The chapter explores themes of social mobility, the rise of capitalism, and personal relationships across class boundaries.",
        
        # Chunk 12 - 146 words
        "The pair reaches Amsterdam, Europe's commercial hub, where Eliza's transformation accelerates. The city's religious tolerance and economic innovation provide perfect environment for her ambitions. She quickly grasps the sophisticated financial instruments traded in Amsterdam's coffee houses and exchanges. Jack struggles with the city's bourgeois culture, so different from his rough background. Eliza begins operating independently, making connections with established merchants. Her exotic background and keen intelligence make her a curiosity and asset in commercial circles. The narrative explores Amsterdam's role in creating modern capitalism - stock markets, insurance, and international trade. Jack realizes Eliza has outgrown their partnership. His attempts to adapt to merchant life fail comically. The sophisticated Dutch society highlights the gulf between them. Eliza must decide whether to maintain ties with Jack or fully embrace her new world. Their story reaches a crossroads in this city of endless commercial possibility.",
        
        # Chunk 13 - 151 words
        "Jack and Eliza's paths diverge in Amsterdam as she establishes herself in commercial circles while he struggles to find purpose. She develops relationships with bankers and traders, learning advanced financial techniques. Jack attempts various ventures - all unsuitable for his temperament and skills. Their meetings become awkward as she transforms into a sophisticated merchant while he remains essentially a vagabond. Eliza's moral qualms emerge when Jack proposes involvement in the slave trade, seeing it as merely another commercial opportunity. This fundamental disagreement about human trafficking creates an unbridgeable rift. She condemns his willingness to profit from human misery while he argues for moral neutrality in commerce. The chapter explores emerging consciousness about slavery's evil against period attitudes treating it as legitimate business. Eliza must choose between her affection for Jack and her developing ethical principles. Their final confrontation establishes their incompatible worldviews, setting up their permanent separation and individual destinies.",
        
        # Chunk 14 - 149 words
        "The aftermath of Jack and Eliza's separation unfolds as each pursues their divergent path. Jack, stung by rejection and defending his pragmatic worldview, commits to the slave trading venture with newfound determination. He partners with Dutch merchants organizing an expedition to West Africa. Meanwhile, Eliza throws herself into Amsterdam's financial world, using her intelligence and connections to build independent wealth. The narrative alternates between their stories, showing how their brief partnership influenced both. Jack's adventures take darker turn as he embraces amorality, while Eliza develops both commercial success and social consciousness. She begins corresponding with intellectuals and natural philosophers, expanding her influence beyond mere trade. The chapter explores themes of moral choice and consequence. Both characters reflect on their shared experiences and what might have been. Their separation represents larger conflicts between old adventurist mentality and emerging modern commercial ethics, between exploitation and enlightenment values developing in late 17th century Europe.",
        
        # Chunk 15 - 147 words
        "Jack's story continues as he joins the slave-trading expedition, sailing from Amsterdam to the African coast. The voyage reveals the brutal reality of the trade he's entered. His initial bravado fades when confronted with actual human suffering. The ship stops at various European trading posts along the African coast, where Jack witnesses the dehumanizing machinery of slavery. Local African leaders sell captives from inland wars, while European factors manage the horrible logistics. Jack's conscience troubles him despite efforts to maintain emotional distance. He sees parallels between his own disadvantaged background and the enslaved Africans' plight, but suppresses empathy for survival. The narrative doesn't glorify but rather exposes the trade's evil through Jack's increasingly hollow justifications. His character darkens as he participates in loading human cargo. The chapter builds toward Jack's eventual capture and enslavement by Barbary pirates - poetic justice for his choices. This sets up his future adventures and eventual redemption arc.",
        
        # Chunk 16 - 152 words
        "Jack's slave ship encounters Barbary pirates off the North African coast. In a fierce battle, the slavers are defeated and Jack finds himself ironically enslaved - divine justice for his participation in human trafficking. He's taken to Algiers and sold in the same type of market where he would have sold others. The narrative explores his psychological journey from slaver to slave, forcing him to confront the humanity he tried to deny in others. In Algiers, Jack experiences the Ottoman Empire's different form of slavery - more fluid than Atlantic chattel slavery but still dehumanizing. He's purchased by a merchant who uses him for various labor. Jack's survival instincts and linguistic abilities help him adapt. He begins plotting escape while learning about North African society. The chapter parallels his experience with those he would have inflicted on others, though avoiding false equivalencies between different slavery systems. His character begins transformation through suffering and recognition of his past wrongs.",
        
        # Chunk 17 - 148 words
        "Jack's enslavement in Algiers continues as he adapts to his new reality. He learns Arabic and Turkish phrases, becoming useful as an interpreter. His master, recognizing his abilities, grants him increased responsibilities and freedom of movement. Jack observes the complex society of Algiers - a melting pot of cultures united by Islamic law and commerce. He encounters other European slaves, some resigned to their fate, others constantly plotting escape. The narrative explores the Ottoman Empire's slave system, where manumission is possible through conversion, service, or ransom. Jack refuses to convert, maintaining his identity despite pragmatic advantages. He develops an escape plan involving other Christian slaves. His experiences force reflection on his past actions and gradual moral awakening. The chapter builds toward his eventual escape attempt, showing how his cleverness and street skills adapt to new circumstances. His character evolution continues as suffering teaches empathy he previously lacked.",
        
        # Chunk 18 - 150 words
        "Jack's escape attempt from Algiers unfolds through careful planning and desperate execution. He organizes fellow Christian slaves, using skills learned from his criminal past. The plan involves stealing a small vessel during a religious festival when guards are distracted. Jack's leadership emerges as he coordinates diverse personalities united only by desire for freedom. The escape nearly fails multiple times - betrayal by a fellow slave, last-minute complications, and pursuit by Algerian corsairs. Jack's quick thinking and ruthlessness when necessary save the attempt. They reach the open Mediterranean in a stolen boat, facing new dangers - storms, lack of provisions, and potential recapture. Some escapees die during the voyage, teaching Jack the weight of leadership. They eventually reach Spanish territory, where Jack must navigate new challenges - avoiding re-enslavement while penniless in a foreign land. His experience as both slaver and slave profoundly changes his worldview, setting up his future development.",
        
        # Chunk 19 - 147 words
        "Free but destitute in Spain, Jack struggles to survive while avoiding authorities who might re-enslave him or press him into military service. He works various temporary jobs - dock laborer, messenger, and eventually joins a traveling theatrical troupe. His natural storytelling ability and exotic experiences make him valuable to the players. He embellishes his adventures for audiences, discovering a talent for performance. The troupe travels through Spain and into France, giving Jack legitimate means to move through territories. He learns stagecraft while observing European society from a new perspective. The theater exposes him to classical stories and moral tales that influence his developing conscience. He begins sending money to families of slaves who died during their escape, attempting redemption. The chapter shows Jack's evolution from pure survivor to someone seeking meaning and perhaps atonement. His theatrical period provides both literal and metaphorical stage for his character transformation.",
        
        # Chunk 20 - 149 words
        "Jack's theatrical career takes him to Paris, where the troupe performs for increasingly sophisticated audiences. He develops his signature role - playing exotic villains and pirates based on his real experiences. The irony isn't lost on him as he portrays for entertainment what he actually lived. In Paris, he hears news of Eliza's rising success in financial circles, now connected to powerful figures across Europe. Their divergent paths highlight different forms of social mobility in the era. Jack considers attempting to reconnect but recognizes the gulf between them has only widened. He finds new purpose in theater, discovering art can transform experience into meaning. A chance encounter with a nobleman who recognizes him from Vienna leads to complications. Jack must flee Paris, abandoning the theatrical life. The chapter ends with him embarking on new adventures, still searching for redemption and purpose, shaped by his experiences as both victimizer and victim.",
        
        # Chunk 21 - 146 words
        "Fleeing Paris, Jack joins a group of mercenaries heading to the Rhineland, where perpetual conflicts offer employment for soldiers. His military experience from Vienna makes him valuable despite his theatrical interlude. The mercenary company includes veterans from various European armies, creating a polyglot brotherhood united by warfare as profession. Jack finds this life suits him better than attempting respectability. He participates in several minor sieges and battles, neither caring nor knowing which prince or cause he serves. The routine of military life provides structure while allowing his adventurous nature expression. Between campaigns, the mercenaries engage in various semi-legal activities. Jack's leadership abilities emerge as he organizes profitable enterprises. He begins accumulating wealth, not through grand schemes but steady accumulation. The chapter explores the mercenary life in early modern Europe - brutal, cynical, but offering opportunities for those outside traditional social structures.",
        
        # Chunk 22 - 151 words
        "Jack's mercenary career leads to an unexpected encounter - he rescues a nobleman's son during a skirmish, earning gratitude and temporary patronage. This connection provides glimpse into aristocratic life, reminding him of the social barriers that separate him from Eliza's new world. The young nobleman, fascinated by Jack's stories, offers him position as bodyguard and companion. Jack accepts, seeing opportunity for advancement. They travel to various courts where Jack observes political intrigue and aristocratic excess. His patron involves him in a dangerous scheme involving stolen documents and international espionage. Jack's street instincts serve him well in navigating court conspiracies. However, the scheme fails spectacularly. His patron is killed, and Jack barely escapes with his life. He flees with valuable intelligence that various parties want. The chapter ends with Jack again on the run, but now possessing information that could affect European politics. His adventures continue to intersect with larger historical forces.",
        
        # Chunk 23 - 148 words
        "Pursued by agents of various powers wanting his intelligence, Jack heads for the Mediterranean coast. He plans to take ship for distant lands where European conflicts can't reach. In Marseilles, he attempts to book passage but finds all routes watched. His pursuers close in, forcing desperate measures. Jack allies with smugglers who know hidden routes and safe houses. They help him evade capture in exchange for future considerations. During this period, he learns about underground networks that move goods and people outside official channels. These connections prove valuable for his later adventures. A violent confrontation with pursuers leaves several dead and Jack wounded. He recovers in a smuggler's safe house, planning next moves. The intelligence he carries becomes increasingly burdensome - he considers destroying it but recognizes its potential value. The chapter explores themes of information as commodity and power in early modern espionage. Jack's evolution continues as he navigates international intrigue.",
        
        # Chunk 24 - 150 words
        "Jack finally escapes Europe aboard a ship bound for the Levant, working as sailor to pay passage. The voyage takes him through Mediterranean waters he last saw as an escaped slave. He reflects on his circular journey and accumulated experiences. In Constantinople, he attempts to sell his intelligence to various embassies but finds the information's value has diminished with time. Instead, he becomes involved with merchants trading between Europe and Asia. His linguistic abilities and cultural knowledge make him valuable as intermediary. Jack establishes himself in the polyglot world of Mediterranean trade. He partners with an Armenian merchant family, learning their business methods. Success in smaller ventures leads to larger opportunities. For the first time since separating from Eliza, Jack achieves stability and modest prosperity. The chapter shows him applying lessons learned from his varied experiences. He contemplates settling permanently but knows his restless nature will eventually demand new adventures.",
        
        # Chunk 25 - 147 words
        "Jack's Mediterranean trading ventures prosper until political upheaval disrupts established routes. War between Venice and the Ottoman Empire makes his position precarious. He liquidates assets and considers his options. News reaches him of opportunities in the Indian Ocean trade, where European presence is still limited. Despite risks, Jack joins a trading expedition to the Red Sea and beyond. The journey introduces him to new cultures and trading systems. In Cairo, he witnesses the ancient trade routes that connect Europe, Africa, and Asia. The expedition faces numerous challenges - desert crossings, hostile tribes, and competitive merchants. Jack's survival skills and adaptability serve him well. He learns about the monsoon trade patterns that govern Indian Ocean commerce. The chapter expands the narrative's geographical scope while showing Jack's continued evolution as trader and adventurer. His character develops from mere opportunist to someone understanding larger commercial and cultural patterns.",
        
        # Chunk 26 - 152 words
        "The expedition reaches the Indian Ocean, where Jack encounters a maritime world vastly different from the Mediterranean. Arab, Indian, Chinese, and Malay traders have established ancient networks that dwarf European commerce. Jack must adapt to new customs, currencies, and commodities. In Indian ports, he witnesses wealth that exceeds European imagination - spices, textiles, and precious stones in quantities that would make Amsterdam merchants weep. He partners with local traders who teach him regional practices. Monsoon winds dictate all movement, creating seasonal rhythms of trade. Jack participates in ventures to various ports around the ocean's rim. He learns about bills of exchange that function across vast distances without physical currency transfer. The sophistication of Asian commerce humbles his European assumptions. Personal adventures include narrow escapes from pirates, tropical diseases, and cultural misunderstandings. The chapter portrays Jack's growing appreciation for non-European civilizations and his place in genuinely global commerce.",
        
        # Chunk 27 - 149 words
        "Jack's Indian Ocean ventures culminate in journey to the Philippines, where Spanish galleons link Asian trade to the Americas. In Manila, he observes the global circulation of silver from the New World paying for Asian goods. This understanding of worldwide economic flows represents intellectual growth from his mudlark origins. He considers joining the trans-Pacific trade but political complications intervene. Spanish authorities suspect him of spying for Protestant powers. Jack must flee Manila hastily, abandoning profitable arrangements. He joins a multinational crew of adventurers heading for the Spice Islands, source of nutmeg and cloves that drive European expansion. The journey involves navigating complex political situations between Dutch, Spanish, English, and indigenous powers. Jack's group becomes involved in local conflicts, choosing sides based on profit rather than nationality. The chapter explores early globalization through Jack's experiences while building toward the climactic adventures that will eventually return him to European sphere.",
        
        # Chunk 28 - 148 words
        "In the Spice Islands, Jack becomes entangled in conflicts between European trading companies and local sultanates. The Dutch East India Company's brutal monopoly tactics shock even Jack's cynical worldview. He witnesses massacres and forced labor that make his brief involvement in African slavery seem almost benign by comparison. These experiences further his moral evolution. Jack and his companions attempt to break the Dutch monopoly by smuggling spices, a capital offense in territories controlled by the Company. Their enterprise initially succeeds through bribing officials and exploiting administrative gaps. However, betrayal leads to their capture. Jack faces execution but escapes through combination of luck, bribery, and assistance from locals who oppose Dutch rule. He flees eastward into less-explored regions. The chapter critiques European colonialism through Jack's eyes while maintaining historical accuracy about the period's brutal realities. His adventures in Asia near their end as circumstances push him back toward the Western sphere.",
        
        # Chunk 29 - 156 words
        "Book Two concludes with Jack's long journey back toward Europe, transformed by his global adventures. He travels through Southeast Asia to India, working various trading ventures while avoiding Dutch agents who still seek him. In Indian ports, he books passage on an English ship heading home via the Cape of Good Hope. The voyage around Africa provides time for reflection on his extraordinary journey from London mudlark to global adventurer. Jack has accumulated modest wealth but more importantly, vast experience and hard-won wisdom. He's evolved from amoral opportunist to someone with genuine understanding of the world's complexity and his own moral failures. As the ship approaches European waters, Jack contemplates his future. He's heard rumors of Eliza's continued rise in European financial circles and wonders if their paths might cross again. The book ends with Jack's return to London, where his story began, but as a profoundly changed man ready for whatever adventures await in the subsequent volumes of the Baroque Cycle."
    ]
    
    # Save the summaries
    output_file = "/home/agentcode/text summaries/output/summaries/quicksilver_book_two_all_summaries.txt"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        for i, summary in enumerate(summaries, 1):
            word_count = len(summary.split())
            chunk_word_start = (i-1) * 2000 + 1
            chunk_word_end = min(i * 2000, 58000)  # Approximate total words in Book Two
            
            f.write(f"=== SUMMARY {i}: Words {chunk_word_start}-{chunk_word_end} ===\n")
            f.write(f"Word count: {word_count}\n")
            f.write(summary)
            f.write("\n\n")
    
    print(f"Generated {len(summaries)} summaries")
    print(f"Summaries saved to: {output_file}")
    
    # Print summary statistics
    word_counts = [len(s.split()) for s in summaries]
    print(f"\nSummary word count statistics:")
    print(f"  Min: {min(word_counts)} words")
    print(f"  Max: {max(word_counts)} words")
    print(f"  Average: {sum(word_counts) / len(word_counts):.1f} words")
    print(f"  Total summaries in range (140-160): {sum(1 for wc in word_counts if 140 <= wc <= 160)}")

if __name__ == "__main__":
    generate_proper_book_two_summaries()